import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dist = resolve(root, process.argv[2] ?? "dist");
const generated = new Set(["sw.js", "offline-inventory.json"]);
const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");

async function inventory(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries.sort((a, b) =>
    a.name.localeCompare(b.name, "en"),
  )) {
    const absolute = join(directory, entry.name);
    const path = relative(dist, absolute).split(sep).join("/");
    if (entry.isSymbolicLink())
      throw new Error(`Build assets must not be symlinks: ${path}`);
    if (entry.isDirectory()) files.push(...(await inventory(absolute)));
    else if (entry.isFile() && !generated.has(path)) {
      const bytes = await readFile(absolute);
      files.push({ path, bytes: bytes.byteLength, sha256: sha256(bytes) });
    }
  }
  return files;
}

const assets = await inventory(dist);
if (!assets.some(({ path }) => path === "index.html"))
  throw new Error("Run vite build before offline preparation.");
if (!assets.some(({ path }) => path.startsWith("data/")))
  throw new Error("The complete QUDT baseline must be present in dist/data.");
if (!assets.some(({ path }) => /KaTeX.*\.(woff2?|ttf)$/.test(path)))
  throw new Error("Local KaTeX fonts must be part of the production build.");
const inventoryBytes = Buffer.from(
  `${JSON.stringify({ schema: "hvacr-offline-inventory-v1", assets }, null, 2)}\n`,
);
await writeFile(join(dist, "offline-inventory.json"), inventoryBytes);
assets.push({
  path: "offline-inventory.json",
  bytes: inventoryBytes.byteLength,
  sha256: sha256(inventoryBytes),
});
const buildId = sha256(JSON.stringify(assets)).slice(0, 20);
const byteCount = assets.reduce((total, asset) => total + asset.bytes, 0);

// The worker's location determines the base path; no deployment origin is embedded.
const worker = `/* Generated by scripts/prepare-offline.mjs. Do not edit. */
const BUILD_ID = ${JSON.stringify(buildId)};
const ASSETS = ${JSON.stringify(assets)};
const BYTE_COUNT = ${byteCount};
const BASE = new URL('./', self.location.href);
const CACHE_NAME = 'hvacr-m0-v1:' + encodeURIComponent(BASE.href) + ':' + BUILD_ID;
const READY_KEY = new URL('.hvacr-offline-ready', BASE).href;
const urls = ASSETS.map(asset => new URL(asset.path.split('/').map(encodeURIComponent).join('/'), BASE).href);
const assetUrls = new Set(urls);
const hex = buffer => Array.from(new Uint8Array(buffer), value => value.toString(16).padStart(2, '0')).join('');

async function isComplete(cache) {
  const marker = await cache.match(READY_KEY);
  if (!marker || (await marker.json()).buildId !== BUILD_ID) return false;
  for (const url of urls) if (!await cache.match(url)) return false;
  return true;
}

async function prepare() {
  const cache = await caches.open(CACHE_NAME);
  if (await isComplete(cache)) return;
  let next = 0;
  let failed = false;
  // A small queue avoids opening every full-data/font request at once on a phone.
  const jobs = Array.from({ length: Math.min(4, ASSETS.length) }, async () => {
    while (!failed && next < ASSETS.length) {
      const index = next++;
      const asset = ASSETS[index];
      try {
        const response = await fetch(new Request(urls[index], { cache: 'reload', credentials: 'same-origin', redirect: 'error' }));
        if (!response.ok || response.type === 'opaque') throw new Error('Cannot prepare ' + asset.path);
        const bytes = await response.clone().arrayBuffer();
        if (bytes.byteLength !== asset.bytes || hex(await crypto.subtle.digest('SHA-256', bytes)) !== asset.sha256) {
          throw new Error('Build changed during preparation: ' + asset.path);
        }
        await cache.put(urls[index], response);
      } catch (error) {
        failed = true;
        throw error;
      }
    }
  });
  const results = await Promise.allSettled(jobs);
  const failure = results.find(result => result.status === 'rejected');
  if (failure) {
    // Only this scope's incomplete build cache is removed; other apps and versions survive.
    await caches.delete(CACHE_NAME);
    throw failure.reason;
  }
  await cache.put(READY_KEY, new Response(JSON.stringify({ buildId: BUILD_ID }), { headers: { 'Content-Type': 'application/json' } }));
  if (!await isComplete(cache)) {
    await caches.delete(CACHE_NAME);
    throw new Error('The complete offline build could not be retained.');
  }
}

self.addEventListener('install', event => event.waitUntil(prepare()));
// Updates wait for all old app tabs to close: never force-replace a running release.
// Do not delete prior caches here; storage cleanup needs a deliberate later lifecycle.
self.addEventListener('activate', event => event.waitUntil(Promise.resolve()));
self.addEventListener('message', event => {
  if (event.data?.type !== 'HVACR_OFFLINE_STATUS' || !event.ports[0]) return;
  event.waitUntil((async () => {
    try {
      const ready = await isComplete(await caches.open(CACHE_NAME));
      event.ports[0].postMessage({ ready, buildId: BUILD_ID, assetCount: ASSETS.length, byteCount: BYTE_COUNT });
    } catch {
      event.ports[0].postMessage({ ready: false, buildId: BUILD_ID });
    }
  })());
});

self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== BASE.origin || !url.pathname.startsWith(BASE.pathname)) return;
  const canonical = new URL(url.pathname, BASE).href;
  const key = request.mode === 'navigate' && (url.pathname === BASE.pathname || url.pathname === BASE.pathname + 'index.html')
    ? new URL('index.html', BASE).href
    : canonical;
  if (!assetUrls.has(key)) return;
  event.respondWith((async () => {
    const response = await (await caches.open(CACHE_NAME)).match(key);
    // Never fill holes with files from another release. Reprepare online if storage was lost.
    return response ?? new Response('Offline preview assets are missing. Reconnect and prepare this app again.', {
      status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' }
    });
  })());
});
`;
await writeFile(join(dist, "sw.js"), worker);
console.log(
  `Offline preview ${buildId}: ${assets.length} local assets, ${byteCount.toLocaleString("en-US")} bytes.`,
);
